### ISSUE TITLE
[Feature] Container Registry Publisher prefixes

### ISSUE THREAD

**Issue by TorinAsakura** [atls/raijin#69]
### С чем связан запрос на фичу?
Паблишер должен генерировать префиксы на основе названии веток

### Расскажите как вы это себе видите
- необходимо получать название ветки https://octokit.github.io/rest.js/v18#repos
- проверять есть в названии спец. символы
- если спецсимволов нет - генерировать префикс на основе имени ветки
- иначе - генерировать имя ветки только по символам идущим до спец. символа

### Приложите примеры реализаций
https://github.com/Atlantis-Lab/actl/blob/feature/actl-container-registry-publisher/packages/actl-cr-publisher/src/commands/publish.ts#L27

**Comment by TFK70** [comment]
@TorinAsakura 
 1. Получить название ветки (`dev`/`master` и т.п.)
Сделать это с помощью следующего апи: https://docs.github.com/en/rest/reference/repos#list-branches
2. Применить к полученному regExp, чтобы взять название ветки только до спец. символа
3. Подставить название ветки. Точнее:

**Заменить это:**

```javascript
const version = `dev-${sha}`
```

**На это:**

```javascript
const version = `${branch}-${sha}`
```

**Comment by TFK70** [comment]
@TorinAsakura средствами октокита же можно такое реализовать?

```javascript
export const getBranchName = async (): Promise<any> => {
  const { owner, repo, branch } = await octokit.???

  const branches = await octokit.repos.getBranch({
    owner,
    repo,
    branch
  })
}
```

Имеется ввиду получить owner,repo и branch из контекста
